name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: olafurpg/setup-scala@v5
      with:
        java-version: openjdk@1.8
    - name: Show mvn version
      run: mvn -version
    - name: Build with Maven
      run: mvn clean install dependency:copy-dependencies # mvn -B package --file pom.xml
    - name: Build the Docker image
      run: docker build  --file docker/build/Dockerfile-sedml-solver --tag crbm/biosimulations_copasi_api:latest .
