name: Build sample Java Maven project
 
on: [push, pull_request]
 
jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: 1.8
    name: Java 1.8 compile
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn clean install dependency:copy-dependencies
